// app/api/reuniao-sistematica/route.ts
import { NextResponse, NextRequest } from "next/server";

const HOST         = process.env.DATABRICKS_HOST;
const TOKEN        = process.env.DATABRICKS_TOKEN;
const PATH         = process.env.DATABRICKS_SQL_HTTP_PATH;
const WAREHOUSE_ID = PATH?.split("/").pop();

async function runQuery(statement: string) {
  const res = await fetch(`${HOST}/api/2.0/sql/statements`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      warehouse_id: WAREHOUSE_ID,
      statement,
      wait_timeout: "30s",
      on_wait_timeout: "CONTINUE",
    }),
  });

  if (!res.ok) throw new Error(`Databricks HTTP ${res.status}: ${await res.text()}`);

  let result = await res.json();
  let attempts = 0;

  while (
    (result.status?.state === "PENDING" || result.status?.state === "RUNNING") &&
    attempts < 60
  ) {
    await new Promise(r => setTimeout(r, 1000));
    attempts++;
    const poll = await fetch(
      `${HOST}/api/2.0/sql/statements/${result.statement_id}`,
      { headers: { "Authorization": `Bearer ${TOKEN}` } }
    );
    result = await poll.json();
  }

  if (result.status?.state !== "SUCCEEDED")
    throw new Error(`Query falhou: ${JSON.stringify(result.status)}`);

  const cols: string[] = result.manifest.schema.columns.map((c: any) => c.name);
  const rows: any[][]  = result.result.data_array ?? [];
  return rows.map(row => Object.fromEntries(cols.map((col, i) => [col, row[i]])));
}

const ROTAS_MAO = [
  'ROTA_1','ROTA_2','ROTA_3','ROTA_4','ROTA_5','ROTA_6','ROTA_7','ROTA_8',
  'ROTA_9','ROTA_10','ROTA_11','ROTA_12','ROTA_13','ROTA_14','ROTA_15','ROTA_16',
  'ROTA_17','ROTA_18','ROTA_19','ROTA_20','ROTA_21','ROTA_22','ROTA_23','ROTA_24',
  'ROTA_25','ROTA_26','ROTA_27','ROTA_28','ROTA_29','ROTA_30','ROTA_31','ROTA_930',
];

const ROTAS_INTERIOR = [
  'ROTA_102','ROTA_401','ROTA_510','ROTA_520','ROTA_530','ROTA_531','ROTA_560','ROTA_703','ROTA_704','ROTA_900','ROTA_901','ROTA_910','ROTA_ALTO_ALEGRE_VENDAS_ONLINE','ROTA_ALVARAES_VENDAS_ONLINE','ROTA_ANAMA_VENDAS_ONLINE','ROTA_ANORI_VENDAS_ON_LINE','ROTA_APUI_VENDAS_ONLINE','ROTA_ATALAIA_DO_NORTE_VENDAS_ONLINE','ROTA_AUTAZES_VENDAS_ON_LINE','ROTA_BARCELOS_VENDAS_ONLINE','ROTA_BARREIRINHA_VENDAS_ON_LINE','ROTA_BENJAMIN_CONSTANT_VENDAS_ONLINE','ROTA_BERURI_VENDAS_ONLINE','ROTA_BOA_VISTA_DO_RAMOS_VENDAS_ON_LINE','ROTA_BOL_AMATURA','ROTA_BOL_BOA_VISTA','ROTA_BOL_IRANDUBA','ROTA_BOL_ITACOATIARA','ROTA_BOL_MANACAPURU','ROTA_BOL_NOVA_OLINDA_DO_NORTE','ROTA_BOL_PAC','ROTA_BOL_PORTO_VELHO','ROTA_BOL_PRESIDENTE_FIGUEIREDO','ROTA_BOL_RIO_BRANCO','ROTA_BOL_Sedex','ROTA_BORBA_VENDAS_ON_LINE','ROTA_CAAPIRANGA_VENDAS_ONLINE','ROTA_CACAU_PIRÊRA_VENDAS_ONLINE','ROTA_CANTA_VENDAS_ONLINE','ROTA_CARACARAÍ_VENDAS_ON_LINE','ROTA_CAREIRO_CASTANHO_VENDAS_ON_LINE','ROTA_CAREIRO_DA_VARZEA_VENDAS_ON_LINE','ROTA_CAROEBE_VENDAS_ON_LINE','ROTA_COARI_VENDAS_ON_LINE','ROTA_CODAJAS_VENDAS_ON_LINE','ROTA_CRUZEIRO_DO_SUL_VENDAS_ONLINE','ROTA_FONTE_BOA_VENDAS_ONLINE','ROTA_HUMAITA_VENDAS_ONLINE','ROTA_IRACEMA_VENDAS_ONLINE','ROTA_ITAPIRANGA_VENDAS_ONLINE','ROTA_JURUTI_VENDAS_ONLINE','ROTA_JUTAí_VENDAS_ONLINE','ROTA_LABREA_VENDAS_ONLINE','ROTA_MANAQUIRI_VENDAS_ON_LINE','ROTA_MANICORE_VENDAS_ON_LINE','ROTA_MARAA_VENDAS_ONLINE','ROTA_MAUES_VENDAS_ON_LINE','ROTA_MUCAJAÍ_VENDAS_ON_LINE','ROTA_NHAMUDA_VENDAS_ON_LINE','ROTA_NOVO_AIRAO_VENDAS_ONLINE','ROTA_NOVO_ARIPUANA_VENDAS_ON_LINE','ROTA_NOVO_REMANSO_VENDAS_ONLINE','ROTA_OBIDOS_VENDAS_ONLINE','ROTA_ORIXIMINA_VENDAS_ONLINE','ROTA_PARINTINS_VENDAS_ON_LINE','ROTA_RIO_PRETO_DA_EVA_VENDAS_ON_LINE','ROTA_RORAINOPOLIS_VENDAS_ON_LINE','ROTA_SAO_GABRIEL_DA_CACH_VENDAS_ONLINE','ROTA_SAO_JOAO_DA_BALIZA_VENDAS_ON_LINE','ROTA_SAO_LUIZ_VENDAS_ON_LINE','ROTA_SAO_PAULO_DE_OLIVEN_VENDAS_ONLINE','ROTA_SAO_SEBASTIAO_DO_UA_VENDAS_ONLINE','ROTA_SILVES_VENDAS_ONLINE','ROTA_STA_ISABEL_R_NEGRO_VENDAS_ONLINE','ROTA_TABATINGA_VENDAS_ONLINE','ROTA_TAPAUA_VENDAS_ONLINE','ROTA_TEFE_VENDAS_ON_LINE','ROTA_TERRA_SANTA_VENDAS_ONLINE','ROTA_UARINI_VENDAS_ONLINE','ROTA_URUCARA_VENDAS_ON_LINE','ROTA_URUCURITUBA_VENDAS_ON_LINE','ROTA_VILA_DE_LINDOIA_VENDAS_ONLINE','SEM_ITINERARIO','ROTA_01_ZONA_OESTE_PVH','ROTA_550','ROTA_701','ROTA_702', 'ROTA_BOL_ARIQUEMES', 'ROTA_BOL_JI_PARANA','ROTA_BOL_AEreo'
];

const ROTAS_ACRE_INTERIOR = [
  'ACRELANDIA', 'ASSIS BRASIL', 'BRASILEIA', 'BUJARI', 'CAMPINAS', 'CAPIXABA', 'CRUZEIRO DO SUL', 'CRUZEIRO_DO_SUL', 'EPITACIOLANDIA', 'FEIJO', 'JORDAO', 'MANCIO LIMA', 'MANCIO_LIMA', 'MANOEL URBANO', 'MARECHAL THAUMATURGO', 'PLACIDO DE CASTRO', 'PORTO ACRE', 'PORTO WALTER', 'RODRIGUES ALVES', 'SANTA ROSA DO PURUS', 'SENA MADUREIRA', 'SENADOR GUIOMARD', 'TARAUACA', 'XAPURI'
];

const CIDADES_ROND_INTERIOR = [
  "ABUNA","ALTA FLORESTA D'OESTE","ALTO ALEGRE DOS PARECIS","ALTO PARAISO","ARIQUEMES","BOM FUTURO","BURITIS","CABIXI","CACAULANDIA","CACOAL","CAMPO NOVO DE RONDONIA","CANDEIAS DO JAMARI","CASTANHEIRAS","CEREJEIRAS","COLORADO DO OESTE","CORUMBIARA","COSTA MARQUES","CUJUBIM","ESPIGAO D'OESTE","EXTREMA","GUAJARA-MIRIM","ITAPUA DO OESTE","JARU","JI PARANA","JI-PARANA","MACHADINHO D'OESTE","MIRANTE DA SERRA","MONTE NEGRO","NOVA LONDRINA","NOVA MAMORE","NOVA UNIAO","OURO PRETO DO OESTE","PIMENTA BUENO","PRESIDENTE MEDICI","PRIMAVERA DE RONDONIA","RIO CRESPO","ROLIM DE MOURA","SAO FRANCISCO DO GUAPORE","SAO MIGUEL DO GUAPORE","SERINGUEIRAS","TABAJARA","TEIXEIROPOLIS","THEOBROMA","URUPA","VALE DO ANARI","VALE DO PARAISO","VILHENA","MINISTRO ANDREAZZA"
];

const CIDADES_RORAIMA_INTERIOR = [
  "ALTO ALEGRE","AMAJARI","BONFIM","BV","CANTA","CARACARAI","CAROEBE","EQUADOR","IRACEMA","MUCAJAI","NORMANDIA","NOVA COLINA","NOVA COLINA/ RORAINOPOLIS","NOVO PARAISO","PACARAIMA","RORAINOPLOIS","RORAINOPOLIS","SANTA CECILIA","SAO JOAO DA BALIZA","SÃO JOÃO DA BALIZA","SAO LUIZ","SAO_JOAO_DA_BALIZA","SELECIONE...","VILA EQUADOR","VILA MODERNA","VILA NOVA COLINA"

]

function inList(arr: string[]) {
  //return arr.map(r => `'${r}'`).join(",");
  return arr.map(r => `'${r.replace(/'/g, "''")}'`).join(",");
}

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl;
  const anoParam    = searchParams.get("ano");
  const anoSel      = anoParam ? Number(anoParam) : new Date().getFullYear();
  const anoAnt      = anoSel - 1;

  try {
    const rows = await runQuery(`
      SELECT
        YEAR(DATA_ORD)  AS ano,
        MONTH(DATA_ORD) AS mes,

        -- VAREJO CAPITAL
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_MAO)})
            AND LOCAL_EXPEDICAO = 'LOC_EXP_CENTRO_DISTRIB_MANAUS'
            AND AREA_NEGOCIO = 'Varejo'
          THEN DOCUMENTO_VENDAS END) AS varejo_capital,

        -- VAREJO INTERIOR
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_INTERIOR)})
            AND LOCAL_EXPEDICAO = 'LOC_EXP_CENTRO_DISTRIB_MANAUS'
            AND AREA_NEGOCIO = 'Varejo'
          THEN DOCUMENTO_VENDAS END) AS varejo_interior,

        -- MARKETPLACE CAPITAL
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_MAO)})
            AND LOCAL_EXPEDICAO = 'LOC_EXP_MARKETPLACE'
          THEN DOCUMENTO_VENDAS END) AS mktp_capital,

        -- MARKETPLACE INTERIOR
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_INTERIOR)})
            AND LOCAL_EXPEDICAO = 'LOC_EXP_MARKETPLACE'
          THEN DOCUMENTO_VENDAS END) AS mktp_interior,

        -- MERCADO CAPITAL
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_MAO)})
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_MERCADO_BOL_TARUMA','LOC_EXP_MERCADO_ONLINE')
            AND NOME_FORNECEDOR IS NULL
            AND AREA_NEGOCIO = 'Mercado'
          THEN DOCUMENTO_VENDAS END) AS mercado_capital,

        -- MERCADO INTERIOR
        COUNT(DISTINCT CASE
          WHEN ITINERARIO IN (${inList(ROTAS_INTERIOR)})
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_MERCADO_BOL_TARUMA','LOC_EXP_MERCADO_ONLINE')
            AND NOME_FORNECEDOR IS NULL
            AND AREA_NEGOCIO = 'Mercado'
          THEN DOCUMENTO_VENDAS END) AS mercado_interior,

        -- ACRE CAPITAL
        COUNT(DISTINCT CASE
          WHEN CIDADE IN ('RIO BRANCO', 'RIO_BRANCO')
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_CD_R_BRANCO', 'LOC_EXP_CENTRO_DISTRIB_MANAUS', 'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMA_CRUZEIRO_DO_SUL', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_LOJA_CRUZEIRO_DO_SUL', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE', 'LOC_EXP_RIO_BRANCO')
            AND REGIAO = 'ACRE'
          THEN DOCUMENTO_VENDAS END) AS acre_capital,

        -- ACRE INTERIOR
        COUNT(DISTINCT CASE
          WHEN CIDADE IN (${inList(ROTAS_ACRE_INTERIOR)})
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_CD_R_BRANCO', 'LOC_EXP_CENTRO_DISTRIB_MANAUS', 'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMA_CRUZEIRO_DO_SUL', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_LOJA_CRUZEIRO_DO_SUL', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE', 'LOC_EXP_RIO_BRANCO')
            AND REGIAO = 'ACRE'
          THEN DOCUMENTO_VENDAS END) AS interior_acre,

        -- RONDONIA CAPITAL
        COUNT(DISTINCT CASE
          WHEN CIDADE IN ('PORTO VELHO', 'PORTO_VELHO')
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_CD_PORTO_VELHO', 'LOC_EXP_CENTRO_DISTRIB_MANAUS',  'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_LOJA_PORTO_VELHO', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE', 'LOC_EXP_PORTO_VELHO__SHOPPING')
            AND REGIAO = 'RONDONIA'
          THEN DOCUMENTO_VENDAS END) AS rondonia_capital,

        -- RONDONIA INTERIOR
        COUNT(DISTINCT CASE
          WHEN CIDADE IN (${inList(CIDADES_ROND_INTERIOR)})
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_ARIQUEMES','LOC_EXP_CD_PORTO_VELHO', 'LOC_EXP_CENTRO_DISTRIB_MANAUS',  'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_JI_PARANA', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE')
            AND REGIAO = 'RONDONIA'
          THEN DOCUMENTO_VENDAS END) AS rondonia_interior,

        -- RORAIMA CAPITAL
        COUNT(DISTINCT CASE
          WHEN CIDADE IN ('BOA VISTA', 'BOAVISTA', 'BOA_VISTA')
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_BOA_VISTA', 'LOC_EXP_CD_BOA_VISTA', 'LOC_EXP_CENTRO_DISTRIB_MANAUS',  'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_LOJA_ATAIDE', 'LOC_EXP_LOJA_GETULIO_VARGAS', 'LOC_EXP_LOJA_MAJOR_WILLIAMS', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE')
            AND REGIAO = 'RORAIMA'
          THEN DOCUMENTO_VENDAS END) AS roraima_capital,

        -- RORAIMA INTERIOR
        COUNT(DISTINCT CASE
          WHEN CIDADE IN (${inList(CIDADES_RORAIMA_INTERIOR)})
            AND CONDICAO_EXPEDICAO <> 'CLIENTE_VAI_BUSCAR'
            AND LOCAL_EXPEDICAO IN ('LOC_EXP_BOA_VISTA', 'LOC_EXP_CD_BOA_VISTA', 'LOC_EXP_CENTRO_DISTRIB_MANAUS',  'LOC_EXP_FARMA_BOL_TORRES', 'LOC_EXP_FARMACIA_ONLINE', 'LOC_EXP_LOJA_ATAIDE', 'LOC_EXP_LOJA_GETULIO_VARGAS', 'LOC_EXP_LOJA_MAJOR_WILLIAMS', 'LOC_EXP_MARKETPLACE', 'LOC_EXP_MERCADO_BOL_TARUMA', 'LOC_EXP_MERCADO_ONLINE', 'LOC_EXP_RORAINOPOLIS')
            AND REGIAO = 'RORAIMA'
          THEN DOCUMENTO_VENDAS END) AS roraima_interior

      FROM cd_bemol.torre_controle.tab_pedidos
      WHERE YEAR(DATA_ORD) IN (${anoSel}, ${anoAnt})
      GROUP BY YEAR(DATA_ORD), MONTH(DATA_ORD)
      ORDER BY ano, mes
    `);

    return NextResponse.json({ ok: true, data: rows });

  } catch (err: any) {
    console.error("[Reunião Sistemática] Erro:", err.message);
    return NextResponse.json({ ok: false, error: err.message }, { status: 500 });
  }
}